name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 2.2.1
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  stripe_android:
     git:
      url: https://github.com/HaniMohamed/flutter_stripe
      path: packages/stripe_android
      ref: hani_try_fix_android_bintray_server_down
  stripe_ios: ^2.2.0
  stripe_platform_interface: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3



